# Generated by Django 4.1.1 on 2022-09-07 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_carteira'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ativosdividendos',
            name='dividendo',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
    ]
