version: '3'
services:

  postgres:
    image: postgres
    hostname: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=projetofii
      - POSTGRES_PASSWORD=123456
    volumes:
      - db-data:/var/lib/postgresql/data

  pgadmin4:
    image: dpage/pgadmin4
    hostname: pgadmin4
    container_name: pgadmin4
    ports:
      - 5051:80
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=admin


volumes:
  db-data:
